Update patch set 11
Patch Set 11: Verified-1

Build failed:
/opt/nfs-ganesha/src/Protocols/NFS/nfs4_Compound.c:1072:10: error: use of undeclared identifier 'XPRT_SUSPEND'
                return XPRT_SUSPEND;
                       ^
/opt/nfs-ganesha/src/Protocols/NFS/nfs4_Compound.c:1088:11: error: use of undeclared identifier 'XPRT_SUSPEND'
                        return XPRT_SUSPEND;
                               ^
/opt/nfs-ganesha/src/Protocols/NFS/nfs4_Compound.c:1295:8: error: no member named 'resume_cb' in 'struct svc_xprt'
        xprt->resume_cb = nfs4_compound_resume;
        ~~~~  ^
3 errors generated.
make[2]: *** [Protocols/NFS/CMakeFiles/nfsproto.dir/build.make:154: Protocols/NFS/CMakeFiles/nfsproto.dir/nfs4_Compound.c.o] Error 1
make[2]: Target 'Protocols/NFS/CMakeFiles/nfsproto.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:1046: Protocols/NFS/CMakeFiles/nfsproto.dir/all] Error 2
/opt/nfs-ganesha/src/MainNFSD/nfs_worker_thread.c:1497:11: error: use of undeclared identifier 'XPRT_SUSPEND'
                        return XPRT_SUSPEND;
                               ^
1 error generated.
make[2]: *** [MainNFSD/CMakeFiles/MainServices.dir/build.make:89: MainNFSD/CMakeFiles/MainServices.dir/nfs_worker_thread.c.o] Error 1
/opt/nfs-ganesha/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1088:13: error: no member named 'alloc_cb' in 'struct svc_init_params'
        svc_params.alloc_cb = alloc_nfs_request;
        ~~~~~~~~~~ ^
/opt/nfs-ganesha/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1089:13: error: no member named 'free_cb' in 'struct svc_init_params'
        svc_params.free_cb = free_nfs_request;
        ~~~~~~~~~~ ^
2 errors generated.
make[2]: *** [MainNFSD/CMakeFiles/MainServices.dir/build.make:102: MainNFSD/CMakeFiles/MainServices.dir/nfs_rpc_dispatcher_thread.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/MainServices.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2565: MainNFSD/CMakeFiles/MainServices.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 11
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1