Update patch set 2
Patch Set 2: Verified-1

Build failed:
/opt/nfs-ganesha/src/FSAL_UP/fsal_up_top.c:1791:37: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        struct root_op_context root_ctx = {0, };
                                           ^
                                           {}
1 error generated.
make[2]: *** [MainNFSD/CMakeFiles/FsalCore.dir/build.make:180: MainNFSD/CMakeFiles/FsalCore.dir/__/FSAL_UP/fsal_up_top.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/FsalCore.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2528: MainNFSD/CMakeFiles/FsalCore.dir/all] Error 2
/opt/nfs-ganesha/src/FSAL_UP/fsal_up_top.c:1791:37: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        struct root_op_context root_ctx = {0, };
                                           ^
                                           {}
1 error generated.
make[2]: *** [MainNFSD/CMakeFiles/ganesha.nfsd.dir/build.make:193: MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL_UP/fsal_up_top.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/ganesha.nfsd.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2627: MainNFSD/CMakeFiles/ganesha.nfsd.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1004838 <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1