Update patch set 6
Patch Set 6:

Build failed:
/opt/nfs-ganesha/src/MainNFSD/9p_rdma_dispatcher.c:67:2: error: implicit declaration of function 'rcu_register_thread' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rcu_register_thread();
        ^
/opt/nfs-ganesha/src/MainNFSD/9p_rdma_dispatcher.c:97:2: error: implicit declaration of function 'rcu_unregister_thread' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rcu_unregister_thread();
        ^
/opt/nfs-ganesha/src/MainNFSD/9p_rdma_dispatcher.c:97:2: note: did you mean 'rcu_register_thread'?
/opt/nfs-ganesha/src/MainNFSD/9p_rdma_dispatcher.c:67:2: note: 'rcu_register_thread' declared here
        rcu_register_thread();
        ^
/opt/nfs-ganesha/src/MainNFSD/9p_rdma_dispatcher.c:144:2: error: implicit declaration of function 'rcu_register_thread' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rcu_register_thread();
        ^
/opt/nfs-ganesha/src/MainNFSD/9p_rdma_dispatcher.c:195:2: error: implicit declaration of function 'rcu_unregister_thread' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rcu_unregister_thread();
        ^
/opt/nfs-ganesha/src/MainNFSD/9p_rdma_dispatcher.c:335:2: error: implicit declaration of function 'rcu_register_thread' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rcu_register_thread();
        ^
/opt/nfs-ganesha/src/MainNFSD/9p_rdma_dispatcher.c:426:2: error: implicit declaration of function 'rcu_unregister_thread' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rcu_unregister_thread();
        ^
6 errors generated.
make[2]: *** [MainNFSD/CMakeFiles/MainServices.dir/build.make:193: MainNFSD/CMakeFiles/MainServices.dir/9p_rdma_dispatcher.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/MainServices.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2565: MainNFSD/CMakeFiles/MainServices.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 6