Update patch set 1
Patch Set 1: Verified-1

Build failed:
/opt/nfs-ganesha/src/FSAL/FSAL_CEPH/handle.c:1484:23: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
        if (my_fd->openflags && FSAL_O_TRUNC)
                             ^  ~~~~~~~~~~~~
/opt/nfs-ganesha/src/FSAL/FSAL_CEPH/handle.c:1484:23: note: use '&' for a bitwise operation
        if (my_fd->openflags && FSAL_O_TRUNC)
                             ^~
                             &
/opt/nfs-ganesha/src/FSAL/FSAL_CEPH/handle.c:1484:23: note: remove constant to silence this warning
        if (my_fd->openflags && FSAL_O_TRUNC)
                            ~^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/build.make:89: FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/handle.c.o] Error 1
make[2]: Target 'FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:1957: FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/all] Error 2
/opt/nfs-ganesha/src/FSAL/FSAL_RGW/handle.c:1166:24: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
        if (handle->openflags && FSAL_O_TRUNC)
                              ^  ~~~~~~~~~~~~
/opt/nfs-ganesha/src/FSAL/FSAL_RGW/handle.c:1166:24: note: use '&' for a bitwise operation
        if (handle->openflags && FSAL_O_TRUNC)
                              ^~
                              &
/opt/nfs-ganesha/src/FSAL/FSAL_RGW/handle.c:1166:24: note: remove constant to silence this warning
        if (handle->openflags && FSAL_O_TRUNC)
                             ~^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [FSAL/FSAL_RGW/CMakeFiles/fsalrgw.dir/build.make:102: FSAL/FSAL_RGW/CMakeFiles/fsalrgw.dir/handle.c.o] Error 1
make[2]: Target 'FSAL/FSAL_RGW/CMakeFiles/fsalrgw.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2013: FSAL/FSAL_RGW/CMakeFiles/fsalrgw.dir/all] Error 2
/opt/nfs-ganesha/src/FSAL/default_methods.c:1302:20: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
        if (fd->openflags && FSAL_O_TRUNC)
                          ^  ~~~~~~~~~~~~
/opt/nfs-ganesha/src/FSAL/default_methods.c:1302:20: note: use '&' for a bitwise operation
        if (fd->openflags && FSAL_O_TRUNC)
                          ^~
                          &
/opt/nfs-ganesha/src/FSAL/default_methods.c:1302:20: note: remove constant to silence this warning
        if (fd->openflags && FSAL_O_TRUNC)
                         ~^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [MainNFSD/CMakeFiles/FsalCore.dir/build.make:128: MainNFSD/CMakeFiles/FsalCore.dir/__/FSAL/default_methods.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/FsalCore.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2528: MainNFSD/CMakeFiles/FsalCore.dir/all] Error 2
/opt/nfs-ganesha/src/FSAL/default_methods.c:1302:20: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
        if (fd->openflags && FSAL_O_TRUNC)
                          ^  ~~~~~~~~~~~~
/opt/nfs-ganesha/src/FSAL/default_methods.c:1302:20: note: use '&' for a bitwise operation
        if (fd->openflags && FSAL_O_TRUNC)
                          ^~
                          &
/opt/nfs-ganesha/src/FSAL/default_methods.c:1302:20: note: remove constant to silence this warning
        if (fd->openflags && FSAL_O_TRUNC)
                         ~^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [MainNFSD/CMakeFiles/ganesha.nfsd.dir/build.make:141: MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/default_methods.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/ganesha.nfsd.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2627: MainNFSD/CMakeFiles/ganesha.nfsd.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 1
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1