Update patch set 2
Patch Set 2: Verified-1

Build failed:
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/export.c:459:3: error: implicit declaration of function 'release_posix_file_system' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                release_posix_file_system(unexportfs);
                ^
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/export.c:459:3: note: did you mean 'release_posix_file_systems'?
/opt/nfs-ganesha/src/include/FSAL/fsal_commonlib.h:118:6: note: 'release_posix_file_systems' declared here
void release_posix_file_systems(void);
     ^
1 error generated.
make[2]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsaldummylustre.dir/build.make:63: FSAL/FSAL_VFS/vfs/CMakeFiles/fsaldummylustre.dir/__/export.c.o] Error 1
make[2]: Target 'FSAL/FSAL_VFS/vfs/CMakeFiles/fsaldummylustre.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2207: FSAL/FSAL_VFS/vfs/CMakeFiles/fsaldummylustre.dir/all] Error 2
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/export.c:459:3: error: implicit declaration of function 'release_posix_file_system' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                release_posix_file_system(unexportfs);
                ^
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/export.c:459:3: note: did you mean 'release_posix_file_systems'?
/opt/nfs-ganesha/src/include/FSAL/fsal_commonlib.h:118:6: note: 'release_posix_file_systems' declared here
void release_posix_file_systems(void);
     ^
1 error generated.
make[2]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/build.make:63: FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/__/export.c.o] Error 1
make[2]: Target 'FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2246: FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/all] Error 2
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/export.c:459:3: error: implicit declaration of function 'release_posix_file_system' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                release_posix_file_system(unexportfs);
                ^
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/export.c:459:3: note: did you mean 'release_posix_file_systems'?
/opt/nfs-ganesha/src/include/FSAL/fsal_commonlib.h:118:6: note: 'release_posix_file_systems' declared here
void release_posix_file_systems(void);
     ^
1 error generated.
make[2]: *** [FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/build.make:76: FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/__/export.c.o] Error 1
make[2]: Target 'FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2302: FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 2
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1