Update patch set 1
Patch Set 1:

(9 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/1040/artifact/failures/ 


**🔴 Checkpatch lint:** `Failed`
```
src/Protocols/NFS/nfs4_op_getattr.c:142: ERROR: code indent should use tabs where possible
src/Protocols/NFS/nfs4_op_getattr.c:142: WARNING: please, no spaces at the start of a line
src/Protocols/NFS/nfs4_op_getattr.c:144: ERROR: code indent should use tabs where possible
src/Protocols/NFS/nfs4_op_getattr.c:144: WARNING: please, no spaces at the start of a line
src/Protocols/NFS/nfs4_op_getattr.c:145: ERROR: code indent should use tabs where possible
src/Protocols/NFS/nfs4_op_getattr.c:145: WARNING: please, no spaces at the start of a line
src/Protocols/NFS/nfs4_op_getattr.c:146: ERROR: code indent should use tabs where possible
src/Protocols/NFS/nfs4_op_getattr.c:146: WARNING: please, no spaces at the start of a line
Checkpatch total: 4 errors, 4 warnings, 14 lines checked
```
**🔴 Clang-format Check:** `Failed`
```
src/Protocols/NFS/nfs4_op_getattr.c:142: clang-format expects formatting for these lines:
clang-format found style deviations
```
**🟢 FSAL GPFS Build:** `Passed`
**🟢 FSAL RGW Build:** `Passed`
**🟢 FSAL VFS Build:** `Passed`
**🟢 FSAL CephFS Build:** `Passed`
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/1040/console

Patch-set: 1
CC: Gerrit User 1005370 <1005370@d5d70762-12d0-45a1-890d-524b12d3f735>
Attention: {"person_ident":"Gerrit User 1038782 \u003c1038782@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"ADD","reason":"Someone else replied on the change"}