Update patch set 1
Patch Set 1: Verified-1

Build failed:
/opt/nfs-ganesha/src/FSAL_UP/fsal_up_async.c:437:14: error: member reference type 'struct fsal_obj_ops *' is a pointer; did you mean to use '->'?
        obj->obj_ops.put_ref(obj);
        ~~~~~~~~~~~~^
                    ->
/opt/nfs-ganesha/src/FSAL_UP/fsal_up_async.c:445:14: error: member reference type 'struct fsal_obj_ops *' is a pointer; did you mean to use '->'?
        obj->obj_ops.get_ref(obj);
        ~~~~~~~~~~~~^
                    ->
/opt/nfs-ganesha/src/FSAL_UP/fsal_up_async.c:448:15: error: member reference type 'struct fsal_obj_ops *' is a pointer; did you mean to use '->'?
                obj->obj_ops.put_ref(obj);
                ~~~~~~~~~~~~^
                            ->
3 errors generated.
make[2]: *** [MainNFSD/CMakeFiles/FsalCore.dir/build.make:193: MainNFSD/CMakeFiles/FsalCore.dir/__/FSAL_UP/fsal_up_async.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/FsalCore.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2528: MainNFSD/CMakeFiles/FsalCore.dir/all] Error 2
/opt/nfs-ganesha/src/FSAL_UP/fsal_up_async.c:437:14: error: member reference type 'struct fsal_obj_ops *' is a pointer; did you mean to use '->'?
        obj->obj_ops.put_ref(obj);
        ~~~~~~~~~~~~^
                    ->
/opt/nfs-ganesha/src/FSAL_UP/fsal_up_async.c:445:14: error: member reference type 'struct fsal_obj_ops *' is a pointer; did you mean to use '->'?
        obj->obj_ops.get_ref(obj);
        ~~~~~~~~~~~~^
                    ->
/opt/nfs-ganesha/src/FSAL_UP/fsal_up_async.c:448:15: error: member reference type 'struct fsal_obj_ops *' is a pointer; did you mean to use '->'?
                obj->obj_ops.put_ref(obj);
                ~~~~~~~~~~~~^
                            ->
3 errors generated.
make[2]: *** [MainNFSD/CMakeFiles/ganesha.nfsd.dir/build.make:206: MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL_UP/fsal_up_async.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/ganesha.nfsd.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2627: MainNFSD/CMakeFiles/ganesha.nfsd.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 1
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1