Update patch set 1
Patch Set 1: Verified-1

Build proxy failed:
/opt/nfs-ganesha/src/Protocols/NFS/nfs4_op_read.c: In function ‘nfs4_read_cb’:
/opt/nfs-ganesha/src/Protocols/NFS/nfs4_op_read.c:74:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < read_arg->iov_count; ++i) {
   ^
/opt/nfs-ganesha/src/Protocols/NFS/nfs4_op_read.c:74:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [Protocols/NFS/CMakeFiles/nfsproto.dir/nfs4_op_read.c.o] Error 1
/opt/nfs-ganesha/src/Protocols/NFS/nfs3_read.c: In function ‘nfs3_read_cb’:
/opt/nfs-ganesha/src/Protocols/NFS/nfs3_read.c:122:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < read_arg->iov_count; ++i) {
  ^
/opt/nfs-ganesha/src/Protocols/NFS/nfs3_read.c:122:2: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [Protocols/NFS/CMakeFiles/nfsproto.dir/nfs3_read.c.o] Error 1
make[2]: Target `Protocols/NFS/CMakeFiles/nfsproto.dir/build' not remade because of errors.
make[1]: *** [Protocols/NFS/CMakeFiles/nfsproto.dir/all] Error 2
/opt/nfs-ganesha/src/FSAL/FSAL_MEM/mem_handle.c: In function ‘mem_read2’:
/opt/nfs-ganesha/src/FSAL/FSAL_MEM/mem_handle.c:1596:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < read_arg->iov_count; i++) {
  ^
/opt/nfs-ganesha/src/FSAL/FSAL_MEM/mem_handle.c:1596:2: note: use option -std=c99 or -std=gnu99 to compile your code
/opt/nfs-ganesha/src/FSAL/FSAL_MEM/mem_handle.c: In function ‘mem_write2’:
/opt/nfs-ganesha/src/FSAL/FSAL_MEM/mem_handle.c:1698:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < write_arg->iov_count; i++) {
  ^
make[2]: *** [FSAL/FSAL_MEM/CMakeFiles/fsalmem.dir/mem_handle.c.o] Error 1
make[2]: Target `FSAL/FSAL_MEM/CMakeFiles/fsalmem.dir/build' not remade because of errors.
make[1]: *** [FSAL/FSAL_MEM/CMakeFiles/fsalmem.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `default_target' not remade because of errors.

Patch-set: 1
Label: Verified=-1