Update patch set 15
Patch Set 15:

(2 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/test-mani-gpfs/64/artifact/failures/ 


**🔴 Checkpatch lint:** `Failed`
```
src/os/freebsd/subr.c:51: ERROR: trailing whitespace
Checkpatch total: 1 errors, 0 warnings, 23 lines checked
```
**🔴 Clang-format Check:** `Failed`
```
src/os/freebsd/subr.c:51: clang-format expects formatting for these lines:
clang-format found style deviations
```
**🟢 FSAL VFS Build:** `Passed`
**🟢 FSAL GPFS Build:** `Passed`
**🟢 FSAL RGW Build:** `Passed`
**🟢 FSAL CephFS Build:** `Passed`
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/test-mani-gpfs/64/console

Patch-set: 15