libganesha_monitoring file not found
During packaging, the below error is observed

Processing files: ganesha_monitoring-7-dev.9.el9.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/nfs-ganesha-7-dev.9.el9.x86_64/usr/lib64/libganesha_monitoring*

Due to the recent move of monitoring module to ntirpc repo, we
are modifying the library to match with the enable.

Change-Id: Ief5fa6f23de5c4a785a55a0eb3dfca9e610b66e1
Signed-off-by: Pragadeeswaran Sathyanarayanan <pragadeeswaran.sathyanarayanan@ibm.com>