Update patch set 1
Patch Set 1: Verified-1

Build failed:
/usr/lib64/libpthread_nonshared.a(pthread_atfork.oS): In function `__pthread_atfork':
(.text+0x0): multiple definition of `__pthread_atfork'
/usr/lib64/libpthread_nonshared.a(pthread_atfork.oS):(.text+0x0): first defined here
/usr/lib64/libpthread_nonshared.a(pthread_atfork.oS): In function `__pthread_atfork':
(.text+0x0): multiple definition of `pthread_atfork'
/usr/lib64/libpthread_nonshared.a(pthread_atfork.oS):(.text+0x0): first defined here
../support/libhash.a(murmur3.c.o): In function `MurmurHash3_x86_32':
/opt/nfs-ganesha/src/support/murmur3.c:88: undefined reference to `rotl32'
/opt/nfs-ganesha/src/support/murmur3.c:92: undefined reference to `rotl32'
/opt/nfs-ganesha/src/support/murmur3.c:110: undefined reference to `rotl32'
../support/libhash.a(murmur3.c.o): In function `MurmurHash3_x86_128':
/opt/nfs-ganesha/src/support/murmur3.c:154: undefined reference to `rotl32'
/opt/nfs-ganesha/src/support/murmur3.c:158: undefined reference to `rotl32'
../support/libhash.a(murmur3.c.o):/opt/nfs-ganesha/src/support/murmur3.c:163: more undefined references to `rotl32' follow
../support/libhash.a(murmur3.c.o): In function `MurmurHash3_x64_128':
/opt/nfs-ganesha/src/support/murmur3.c:307: undefined reference to `rotl64'
/opt/nfs-ganesha/src/support/murmur3.c:311: undefined reference to `rotl64'
/opt/nfs-ganesha/src/support/murmur3.c:316: undefined reference to `rotl64'
/opt/nfs-ganesha/src/support/murmur3.c:320: undefined reference to `rotl64'
/opt/nfs-ganesha/src/support/murmur3.c:348: undefined reference to `rotl64'
../support/libhash.a(murmur3.c.o):/opt/nfs-ganesha/src/support/murmur3.c:369: more undefined references to `rotl64' follow
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [MainNFSD/CMakeFiles/ganesha.nfsd.dir/build.make:141: MainNFSD/ganesha.nfsd] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/ganesha.nfsd.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:1920: MainNFSD/CMakeFiles/ganesha.nfsd.dir/all] Error 2
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsalnull.dir/handle.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsalproxy.dir/handle.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsalceph.dir/main.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsalrgw.dir/up.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsalgpfs.dir/main.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsaldummylustre.dir/__/export.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsalvfs.dir/__/export.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsalxfs.dir/main.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsalgluster.dir/main.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
/usr/bin/ld: Warning: size of symbol `posix_file_systems' changed from 16 in CMakeFiles/fsalmem.dir/mem_export.c.o to 64 in /opt/nfs-ganesha/build/MainNFSD/libganesha_nfsd.so
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 1
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1