Update patch set 4
Patch Set 4: Verified-1

Build failed:
/opt/nfs-ganesha/src/Protocols/NFS/nfs4_op_readdir.c:656:31: error: use of undeclared identifier 'EXPORT_OPTION_SECLABEL_SET'
            op_ctx_export_has_option(EXPORT_OPTION_SECLABEL_SET))
                                     ^
1 error generated.
make[2]: *** [Protocols/NFS/CMakeFiles/nfsproto.dir/build.make:622: Protocols/NFS/CMakeFiles/nfsproto.dir/nfs4_op_readdir.c.o] Error 1
make[2]: Target 'Protocols/NFS/CMakeFiles/nfsproto.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:1046: Protocols/NFS/CMakeFiles/nfsproto.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 4
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1