Update patch set 6
Patch Set 6:

Can't say tests stdout/err help much...

For basic:
./test2: File and directory removal test
	./test2: (/mnt/sigmund/test3b.ZjVTZlo/cthon-b/dir.0/dir.0/dir.0) ./runtests: line 32:  1157 Segmentation fault      (core dumped) ./test2 $TESTARG
ERROR: ERROR while running cthon04's basic tests


for special:
second check for lost reply on non-idempotent requests
testing 50 idempotencies in directory "testdir"
rmdir 2: Directory not empty
ERROR: ERROR while running cthon04's special tests


It's interesting, it says directory not empty but the directory is removed anyway.

Easy enough to reproduce with 9P:
mkdir test; touch test/foo; rm -f test/foo; rmdir test

The latest rmdir will fail with ENOTEMPTY but remove the directory anyway.

Patch-set: 6
Reviewer: Dominique Martinet <1003556@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=0