Update patch set 1
Patch Set 1: Verified-1

Build failed:
/export/nfs-ganesha/src/support/export_mgr.c:1285:31: error: use of undeclared identifier 'state'; did you mean 'static'?
                (struct showexports_state *)state;
                                            ^~~~~
                                            static
/export/nfs-ganesha/src/support/export_mgr.c:1285:31: error: expected expression
2 errors generated.
make[2]: *** [support/CMakeFiles/support.dir/export_mgr.c.o] Error 1
make[2]: Target 'support/CMakeFiles/support.dir/build' not remade because of errors.
make[1]: *** [support/CMakeFiles/support.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 1
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1