Update patch set 1
Patch Set 1: Verified-1

Build proxy failed:
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/file.c: In function ‘vfs_fallocate’:
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/file.c:1522:19: error: ‘FALLOC_FL_PUNCH_HOLE’ undeclared (first use in this function)
    allocate ? 0 : FALLOC_FL_PUNCH_HOLE,
                   ^
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/file.c:1522:19: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsallustre.dir/__/file.c.o] Error 1
make[2]: Target `FSAL/FSAL_VFS/vfs/CMakeFiles/fsallustre.dir/build' not remade because of errors.
make[1]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsallustre.dir/all] Error 2
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/file.c: In function ‘vfs_fallocate’:
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/file.c:1522:19: error: ‘FALLOC_FL_PUNCH_HOLE’ undeclared (first use in this function)
    allocate ? 0 : FALLOC_FL_PUNCH_HOLE,
                   ^
/opt/nfs-ganesha/src/FSAL/FSAL_VFS/file.c:1522:19: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/__/file.c.o] Error 1
make[2]: Target `FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/build' not remade because of errors.
make[1]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `default_target' not remade because of errors.

Patch-set: 1
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1