Update patch set 3
Patch Set 3:

(7 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/610/artifact/failures/ 


**🔴 Clang-format Check:** `Failed`
```
src/FSAL/commonlib.c:2820: clang-format expects formatting for these lines:
clang-format found style deviations
```
**🔴 Checkpatch lint:** `Failed`
```
src/FSAL/commonlib.c:2820: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2820: WARNING: please, no spaces at the start of a line
src/FSAL/commonlib.c:2821: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2821: WARNING: please, no spaces at the start of a line
src/FSAL/commonlib.c:2822: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2822: WARNING: please, no spaces at the start of a line
Checkpatch total: 3 errors, 3 warnings, 68 lines checked
```
**🟢 FSAL VFS Build:** `Passed`
**🟢 FSAL GPFS Build:** `Passed`
**🟢 FSAL RGW Build:** `Passed`
**🟢 FSAL CephFS Build:** `Passed`
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/610/console

Patch-set: 3