Update patch set 1
Patch Set 1: Verified-1

Build failed:
/export/nfs-ganesha/src/SAL/nfs4_clientid.c:328:30: error: too many arguments to function call, expected single argument 'gd', have 2 arguments
                unref_svc_rpc_gss_data(gd, 0);
                ~~~~~~~~~~~~~~~~~~~~~~     ^
/export/nfs-ganesha/src/libntirpc/ntirpc/rpc/gss_internal.h:114:1: note: 'unref_svc_rpc_gss_data' declared here
static inline void
^
1 error generated.
make[2]: *** [SAL/CMakeFiles/sal.dir/nfs4_clientid.c.o] Error 1
make[2]: Target 'SAL/CMakeFiles/sal.dir/build' not remade because of errors.
make[1]: *** [SAL/CMakeFiles/sal.dir/all] Error 2
/export/nfs-ganesha/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1277:23: error: no member named 'rq_refs' in 'struct svc_req'
        reqdata->r_u.req.svc.rq_refs = 1;
        ~~~~~~~~~~~~~~~~~~~~ ^
/export/nfs-ganesha/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1284:60: error: no member named 'rq_refs' in 'struct svc_req'
        uint32_t refs = atomic_dec_uint32_t(&reqdata->r_u.req.svc.rq_refs);
                                             ~~~~~~~~~~~~~~~~~~~~ ^
/export/nfs-ganesha/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1289:29: error: no member named 'xp_refs' in 'struct svc_xprt'
                 xprt, xprt->xp_fd, xprt->xp_refs,
                                    ~~~~  ^
/export/nfs-ganesha/src/include/log.h:300:30: note: expanded from macro 'LogDebug'
                                                 NIV_DEBUG, format, ## args); \
                                                                       ^~~~
3 errors generated.
make[2]: *** [MainNFSD/CMakeFiles/MainServices.dir/nfs_rpc_dispatcher_thread.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/MainServices.dir/build' not remade because of errors.
make[1]: *** [MainNFSD/CMakeFiles/MainServices.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 1
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1