Update patch set 2
Patch Set 2: Verified-1

Build failed:
/opt/nfs-ganesha/src/SAL/state_deleg.c:508:13: error: variable 'deleg_stats' is uninitialized when used here [-Werror,-Wuninitialized]
        if (deleg_stats->fds_curr_delegations > 0) {
            ^~~~~~~~~~~
/opt/nfs-ganesha/src/SAL/state_deleg.c:503:38: note: initialize the variable 'deleg_stats' to silence this warning
        struct file_deleg_stats *deleg_stats;
                                            ^
                                             = NULL
1 error generated.
make[2]: *** [SAL/CMakeFiles/sal.dir/build.make:128: SAL/CMakeFiles/sal.dir/state_deleg.c.o] Error 1
make[2]: Target 'SAL/CMakeFiles/sal.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:867: SAL/CMakeFiles/sal.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1004838 <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1