For building only VFS FSAL and to fix the following erroris.
nfs-ganesha/src/support/server_stats.c:1313:13:
error: ‘server_dbus_op_stats’ defined but not used
[-Werror=unused-function]
nfs-ganesha/src/support/server_stats.c:1364:13:
error: ‘server_dbus_transportstats’ defined but not used
[-Werror=unused-function]
cc1: all warnings being treated as errors

Change-Id: I2e170ee52c88de443a7a491dde708e63d3326409
Signed-off-by: Krishna Harathi <kharathi@exablox.com>