Update patch set 2
Patch Set 2:

(8 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/608/artifact/failures/ 


**🔴 Clang-format Check:** `Failed`
```
src/FSAL/commonlib.c:2820: clang-format expects formatting for these lines:
clang-format found style deviations
```
**🔴 Checkpatch lint:** `Failed`
```
src/FSAL/commonlib.c:2166: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2167: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2168: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2169: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2170: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2171: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2172: ERROR: code indent should use tabs where possible
Checkpatch total: 7 errors, 0 warnings, 69 lines checked
```
**🟢 FSAL VFS Build:** `Passed`
**🟢 FSAL GPFS Build:** `Passed`
**🟢 FSAL RGW Build:** `Passed`
**🟢 FSAL CephFS Build:** `Passed`
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/608/console

Patch-set: 2
Attention: {"person_ident":"Gerrit User 1005370 \u003c1005370@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"removed on reply"}