Update patch set 1
Patch Set 1: Verified-1

Build failed:
/export/nfs-ganesha/src/Protocols/NFS/nfs_proto_tools.c:2799:15: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
                .attrmask = ATTR_MODE,
                            ^~~~~~~~~
/export/nfs-ganesha/src/include/fsal_types.h:361:19: note: expanded from macro 'ATTR_MODE'
#define ATTR_MODE 0x0000000000000080LL
                  ^~~~~~~~~~~~~~~~~~~~
/export/nfs-ganesha/src/Protocols/NFS/nfs_proto_tools.c:2796:15: note: previous initialization is here
                .attrmask = 0,
                            ^
/export/nfs-ganesha/src/Protocols/NFS/nfs_proto_tools.c:2909:15: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
                .attrmask = ATTR_SPACEUSED,
                            ^~~~~~~~~~~~~~
/export/nfs-ganesha/src/include/fsal_types.h:379:24: note: expanded from macro 'ATTR_SPACEUSED'
#define ATTR_SPACEUSED 0x0000000000010000LL
                       ^~~~~~~~~~~~~~~~~~~~
/export/nfs-ganesha/src/Protocols/NFS/nfs_proto_tools.c:2906:15: note: previous initialization is here
                .attrmask = 0,
                            ^
2 errors generated.
make[2]: *** [Protocols/NFS/CMakeFiles/nfsproto.dir/nfs_proto_tools.c.o] Error 1
make[2]: Target 'Protocols/NFS/CMakeFiles/nfsproto.dir/build' not remade because of errors.
make[1]: *** [Protocols/NFS/CMakeFiles/nfsproto.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 1
Label: Verified=-1