NFS: clean up loglevel handling in nfs4_Compound
The macro unrolling here will cause a minor bug:

In file included from /home/jlayton/git/ganesha/src/libntirpc/ntirpc/rpc/xdr.h:52:0,
                 from /home/jlayton/git/ganesha/src/libntirpc/ntirpc/rpc/xdr_inline.h:53,
                 from /home/jlayton/git/ganesha/src/include/gsh_rpc.h:17,
                 from /home/jlayton/git/ganesha/src/include/uid2grp.h:44,
                 from /home/jlayton/git/ganesha/src/include/fsal_types.h:42,
                 from /home/jlayton/git/ganesha/src/include/fsal_api.h:43,
                 from /home/jlayton/git/ganesha/src/include/fsal.h:62,
                 from /home/jlayton/git/ganesha/src/Protocols/NFS/nfs4_Compound.c:35:
/home/jlayton/git/ganesha/src/Protocols/NFS/nfs4_Compound.c: In function ‘nfs4_Compound’:
/home/jlayton/git/ganesha/src/Protocols/NFS/nfs4_Compound.c:697:27: error: ?: using integer constants in boolean context, the expression will always evaluate to ‘true’ [-Werror=int-in-bool-context]
        bad_pos ? NIV_INFO : NIV_DEBUG,
/home/jlayton/git/ganesha/src/libntirpc/ntirpc/intrinsic.h:32:42: note: in definition of macro ‘unlikely’
 #define unlikely(x)  __builtin_expect(!!(x), 0)
                                          ^
/home/jlayton/git/ganesha/src/Protocols/NFS/nfs4_Compound.c:696:4: note: in expansion of macro ‘LogAtLevel’
    LogAtLevel(COMPONENT_SESSIONS,
    ^~~~~~~~~~

Add some parenthesis to ensure that the evaluation is done properly.
Also, tidy up the LogAtLevel definition a little.

Change-Id: I377bba595c38bf66d6bf34da714be923b685438b
Signed-off-by: Jeff Layton <jlayton@redhat.com>