Update patch set 6
Patch Set 6: Verified-1

Build failed:
/export/nfs-ganesha/src/RPCAL/nfs_dupreq.c:869:6: error: variable 'waitcnt' is uninitialized when used here [-Werror,-Wuninitialized]
                        ++waitcnt;
                          ^~~~~~~
/export/nfs-ganesha/src/RPCAL/nfs_dupreq.c:849:30: note: initialize the variable 'waitcnt' to silence this warning
        uint32_t ix, refcnt, waitcnt;
                                    ^
                                     = 0
1 error generated.
make[2]: *** [RPCAL/CMakeFiles/rpcal.dir/nfs_dupreq.c.o] Error 1
make[2]: Target 'RPCAL/CMakeFiles/rpcal.dir/build' not remade because of errors.
make[1]: *** [RPCAL/CMakeFiles/rpcal.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 6
Label: Verified=-1