Update patch set 4
Patch Set 4:

(3 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/683/artifact/failures/ 


**🔴 Checkpatch lint:** `Failed`
```
src/FSAL/FSAL_CEPH/handle.c:107: ERROR: code indent should use tabs where possible
src/FSAL/FSAL_CEPH/handle.c:107: WARNING: please, no spaces at the start of a line
Checkpatch total: 1 errors, 2 warnings, 26 lines checked
```
**🔴 Clang-format Check:** `Failed`
```
src/FSAL/FSAL_CEPH/handle.c:107: clang-format expects formatting for these lines:
clang-format found style deviations
```
**🟢 FSAL VFS Build:** `Passed`
**🟢 FSAL GPFS Build:** `Passed`
**🟢 FSAL RGW Build:** `Passed`
**🟢 FSAL CephFS Build:** `Passed`
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/683/console

Patch-set: 4
Attention: {"person_ident":"Gerrit User 1005370 \u003c1005370@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"removed on reply"}
Attention: {"person_ident":"Gerrit User 1008938 \u003c1008938@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"ADD","reason":"Someone else replied on the change"}