Update patch set 3
Patch Set 3: Verified-1

Build failed:
/export/nfs-ganesha/src/FSAL/FSAL_VFS/xfs/main.c:101:2: error: unterminated function-like macro invocation
        CONF_ITEM_BOOL("only_one_user", false, vfs_fsal_module,
        ^
/export/nfs-ganesha/src/include/config_parsing.h:577:9: note: macro 'CONF_ITEM_BOOL' defined here
#define CONF_ITEM_BOOL(_name_, _def_, _struct_, _mem_) \
        ^
/export/nfs-ganesha/src/FSAL/FSAL_VFS/xfs/main.c:232:2: error: expected expression
}
 ^
/export/nfs-ganesha/src/FSAL/FSAL_VFS/xfs/main.c:232:2: error: expected '}'
/export/nfs-ganesha/src/FSAL/FSAL_VFS/xfs/main.c:86:42: note: to match this '{'
static struct config_item xfs_params[] = {
                                         ^
/export/nfs-ganesha/src/FSAL/FSAL_VFS/xfs/main.c:100:47: error: expected ';' after top level declarator
                       module.fs_info.auth_exportpath_xdev),
                                                            ^
                                                            ;
4 errors generated.
make[2]: *** [FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/main.c.o] Error 1
make[2]: Target 'FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/build' not remade because of errors.
make[1]: *** [FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 3
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1