Update patch set 2
Patch Set 2:

Build failed:
/opt/nfs-ganesha/src/SAL/recovery/recovery_rados_ng.c:197:48: error: size argument in 'strlcpy' call appears to be size of the source; expected the size of the destination [-Werror,-Wstrlcpy-strlcat-size]
        strlcpy(clientid->cid_recov_tag, cval, strlen(cval) + 1);
                                               ~~~~~~~^~~~~~~~~
1 error generated.
make[2]: *** [SAL/CMakeFiles/sal.dir/build.make:310: SAL/CMakeFiles/sal.dir/recovery/recovery_rados_ng.c.o] Error 1
make[2]: Target 'SAL/CMakeFiles/sal.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:867: SAL/CMakeFiles/sal.dir/all] Error 2
/opt/nfs-ganesha/src/tools/multilock/ml_posix_client.c:146:2: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        array_strcpy(resp.r_data, name);
        ^
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
/opt/nfs-ganesha/src/tools/multilock/ml_posix_client.c:146:2: note: include the header <string.h> or explicitly provide a declaration for 'strlcpy'
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
1 error generated.
make[2]: *** [tools/multilock/CMakeFiles/ml_posix_client.dir/build.make:63: tools/multilock/CMakeFiles/ml_posix_client.dir/ml_posix_client.c.o] Error 1
/opt/nfs-ganesha/src/tools/multilock/ml_functions.c:202:5: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                                array_strcpy(badtoken, "<NULL>");
                                ^
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
/opt/nfs-ganesha/src/tools/multilock/ml_functions.c:202:5: note: include the header <string.h> or explicitly provide a declaration for 'strlcpy'
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
1 error generated.
make[2]: *** [tools/multilock/CMakeFiles/ml_posix_client.dir/build.make:76: tools/multilock/CMakeFiles/ml_posix_client.dir/ml_functions.c.o] Error 1
make[2]: Target 'tools/multilock/CMakeFiles/ml_posix_client.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2746: tools/multilock/CMakeFiles/ml_posix_client.dir/all] Error 2
/opt/nfs-ganesha/src/tools/multilock/ml_console.c:336:4: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                        array_strcpy(client->c_name, client_resp->r_data);
                        ^
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
/opt/nfs-ganesha/src/tools/multilock/ml_console.c:336:4: note: include the header <string.h> or explicitly provide a declaration for 'strlcpy'
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
1 error generated.
make[2]: *** [tools/multilock/CMakeFiles/ml_console.dir/build.make:63: tools/multilock/CMakeFiles/ml_console.dir/ml_console.c.o] Error 1
/opt/nfs-ganesha/src/tools/multilock/ml_functions.c:202:5: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                                array_strcpy(badtoken, "<NULL>");
                                ^
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
/opt/nfs-ganesha/src/tools/multilock/ml_functions.c:202:5: note: include the header <string.h> or explicitly provide a declaration for 'strlcpy'
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
1 error generated.
make[2]: *** [tools/multilock/CMakeFiles/ml_console.dir/build.make:76: tools/multilock/CMakeFiles/ml_console.dir/ml_functions.c.o] Error 1
make[2]: Target 'tools/multilock/CMakeFiles/ml_console.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2784: tools/multilock/CMakeFiles/ml_console.dir/all] Error 2
/opt/nfs-ganesha/src/tools/multilock/ml_glusterfs_client.c:159:2: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        array_strcpy(resp.r_data, name);
        ^
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
/opt/nfs-ganesha/src/tools/multilock/ml_glusterfs_client.c:159:2: note: include the header <string.h> or explicitly provide a declaration for 'strlcpy'
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
1 error generated.
make[2]: *** [tools/multilock/CMakeFiles/ml_glusterfs_client.dir/build.make:63: tools/multilock/CMakeFiles/ml_glusterfs_client.dir/ml_glusterfs_client.c.o] Error 1
/opt/nfs-ganesha/src/tools/multilock/ml_functions.c:202:5: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                                array_strcpy(badtoken, "<NULL>");
                                ^
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
/opt/nfs-ganesha/src/tools/multilock/ml_functions.c:202:5: note: include the header <string.h> or explicitly provide a declaration for 'strlcpy'
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
1 error generated.
make[2]: *** [tools/multilock/CMakeFiles/ml_glusterfs_client.dir/build.make:76: tools/multilock/CMakeFiles/ml_glusterfs_client.dir/ml_functions.c.o] Error 1
make[2]: Target 'tools/multilock/CMakeFiles/ml_glusterfs_client.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2822: tools/multilock/CMakeFiles/ml_glusterfs_client.dir/all] Error 2
/opt/nfs-ganesha/src/tools/multilock/ml_cephfs_client.c:159:2: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        array_strcpy(resp.r_data, name);
        ^
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
/opt/nfs-ganesha/src/tools/multilock/ml_cephfs_client.c:159:2: note: include the header <string.h> or explicitly provide a declaration for 'strlcpy'
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
1 error generated.
make[2]: *** [tools/multilock/CMakeFiles/ml_cephfs_client.dir/build.make:63: tools/multilock/CMakeFiles/ml_cephfs_client.dir/ml_cephfs_client.c.o] Error 1
/opt/nfs-ganesha/src/tools/multilock/ml_functions.c:202:5: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                                array_strcpy(badtoken, "<NULL>");
                                ^
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
/opt/nfs-ganesha/src/tools/multilock/ml_functions.c:202:5: note: include the header <string.h> or explicitly provide a declaration for 'strlcpy'
/opt/nfs-ganesha/src/tools/multilock/multilock.h:162:33: note: expanded from macro 'array_strcpy'
#define array_strcpy(dest, src) strlcpy(dest, src, sizeof(dest))
                                ^
1 error generated.
make[2]: *** [tools/multilock/CMakeFiles/ml_cephfs_client.dir/build.make:76: tools/multilock/CMakeFiles/ml_cephfs_client.dir/ml_functions.c.o] Error 1
make[2]: Target 'tools/multilock/CMakeFiles/ml_cephfs_client.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2860: tools/multilock/CMakeFiles/ml_cephfs_client.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1004838 <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>