Update patch set 3
Patch Set 3: Verified-1

Build failed:
/export/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:146:4: error: implicit declaration of function 'mdcache_reap_and_free_chunk' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        mdcache_reap_and_free_chunk(parent);
                        ^
/export/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:146:4: note: did you mean 'mdcache_clean_dirent_chunk'?
/export/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_int.h:501:6: note: 'mdcache_clean_dirent_chunk' declared here
void mdcache_clean_dirent_chunk(struct dir_chunk *chunk);
     ^
1 error generated.
make[2]: *** [FSAL/Stackable_FSALs/FSAL_MDCACHE/CMakeFiles/fsalmdcache.dir/mdcache_helpers.c.o] Error 1
/export/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:861:51: error: expected expression
                lru = lru_reap_chunk_impl(LRU_ENTRY_L1, parent, [rev_chunk);
                                                                ^
1 error generated.
make[2]: *** [FSAL/Stackable_FSALs/FSAL_MDCACHE/CMakeFiles/fsalmdcache.dir/mdcache_lru.c.o] Error 1
make[2]: Target 'FSAL/Stackable_FSALs/FSAL_MDCACHE/CMakeFiles/fsalmdcache.dir/build' not remade because of errors.
make[1]: *** [FSAL/Stackable_FSALs/FSAL_MDCACHE/CMakeFiles/fsalmdcache.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 3
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1