Update patch set 1
Patch Set 1: Verified-1

Build failed:
/opt/nfs-ganesha/src/MainNFSD/nfs_lib.c:88:12: error: unused variable 'detach_flag' [-Werror,-Wunused-variable]
static int detach_flag = true;
           ^
1 error generated.
make[2]: *** [MainNFSD/CMakeFiles/MainServices.dir/build.make:141: MainNFSD/CMakeFiles/MainServices.dir/nfs_lib.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/MainServices.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2565: MainNFSD/CMakeFiles/MainServices.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 1
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1