Update patch set 2
Patch Set 2: Verified-1

Build failed:
/opt/nfs-ganesha/src/SAL/recovery/recovery_fs_ng.c:1:9: error: '_GNU_SOURCE' macro redefined [-Werror,-Wmacro-redefined]
#define _GNU_SOURCE
        ^
<command line>:2:9: note: previous definition is here
#define _GNU_SOURCE 1
        ^
1 error generated.
make[2]: *** [MainNFSD/CMakeFiles/ganesha_nfsd.dir/build.make:2922: MainNFSD/CMakeFiles/ganesha_nfsd.dir/__/SAL/recovery/recovery_fs_ng.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/ganesha_nfsd.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2613: MainNFSD/CMakeFiles/ganesha_nfsd.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1004838 <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1