Update patch set 1
Patch Set 1: Verified-1

(161 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/1207/artifact/failures/ 


**🔴 Clang-format Check:** `Failed`
```
src/include/client_mgr.h:156: clang-format expects formatting for these lines:
src/include/nfs_proto_functions.h:126: clang-format expects formatting for these lines:
src/include/tsm.h:26: clang-format expects formatting for these lines:
src/include/tsm.h:57: clang-format expects formatting for these lines:
src/include/tsm.h:99: clang-format expects formatting for these lines:
src/support/nfs_read_conf.c:221: clang-format expects formatting for these lines:
src/support/nfs_read_conf.c:537: clang-format expects formatting for these lines:
clang-format found style deviations
```
**🔴 Checkpatch lint:** `Failed`
```
src/MainNFSD/nfs_init.c:1430: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/nfs_init.c:1435: WARNING: line length of 92 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/MainNFSD/transparent_recovery.c:19: WARNING: line length of 97 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:128: WARNING: Missing a blank line after declarations
src/MainNFSD/transparent_recovery.c:148: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:272: WARNING: void function return statements are not generally useful
src/MainNFSD/transparent_recovery.c:281: WARNING: Missing a blank line after declarations
src/MainNFSD/transparent_recovery.c:414: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:735: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:992: WARNING: Missing a blank line after declarations
src/MainNFSD/transparent_recovery.c:1114: WARNING: line length of 103 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1151: WARNING: line length of 90 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1257: WARNING: line length of 126 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1262: WARNING: Missing a blank line after declarations
src/MainNFSD/transparent_recovery.c:1269: WARNING: line length of 87 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1283: WARNING: Too many leading tabs - consider code refactoring
src/MainNFSD/transparent_recovery.c:1284: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1290: WARNING: line length of 85 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1293: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1294: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1295: WARNING: line length of 83 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1298: WARNING: Too many leading tabs - consider code refactoring
src/MainNFSD/transparent_recovery.c:1718: WARNING: Too many leading tabs - consider code refactoring
src/MainNFSD/transparent_recovery.c:1719: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1721: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1723: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1725: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1726: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1729: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1737: WARNING: line length of 88 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1738: WARNING: line length of 86 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1739: WARNING: line length of 88 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1740: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1741: WARNING: line length of 88 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1742: WARNING: line length of 83 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1744: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1747: WARNING: line length of 86 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1764: WARNING: Too many leading tabs - consider code refactoring
src/MainNFSD/transparent_recovery.c:1772: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1775: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1783: WARNING: line length of 88 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1785: WARNING: line length of 88 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1786: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1789: WARNING: line length of 86 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1807: WARNING: Too many leading tabs - consider code refactoring
src/MainNFSD/transparent_recovery.c:1812: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1814: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1816: WARNING: line length of 85 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1819: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1828: WARNING: line length of 89 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1829: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1831: WARNING: line length of 89 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1832: WARNING: line length of 86 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1834: WARNING: line length of 89 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1835: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1837: WARNING: line length of 89 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1838: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:1848: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2200: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2210: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2211: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2213: WARNING: line length of 90 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2214: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2225: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2226: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2228: WARNING: line length of 90 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2229: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2234: WARNING: line length of 97 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2241: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2242: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2244: WARNING: line length of 90 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2245: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2267: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2268: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2270: WARNING: line length of 90 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2271: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2280: WARNING: line length of 87 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2287: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2288: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2290: WARNING: line length of 90 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2291: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2313: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2317: WARNING: line length of 92 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2325: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2326: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2329: WARNING: line length of 91 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2330: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2342: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2343: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2346: WARNING: line length of 91 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2347: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2350: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2362: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2363: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2366: WARNING: line length of 91 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2367: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2370: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2376: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2384: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2385: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2388: WARNING: line length of 91 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2389: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2401: WARNING: line length of 82 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2402: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2405: WARNING: line length of 91 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2406: WARNING: line length of 84 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2409: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2746: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:2795: WARNING: line length of 81 exceeds 80 columns
src/MainNFSD/transparent_recovery.c:3398: ERROR: trailing whitespace
src/MainNFSD/transparent_recovery.c:3461: WARNING: line length of 81 exceeds 80 columns
src/Protocols/NFS/nfs4_op_close.c:324: WARNING: line length of 81 exceeds 80 columns
src/Protocols/NFS/nfs4_op_delegreturn.c:147: WARNING: line length of 81 exceeds 80 columns
src/Protocols/NFS/nfs4_op_lock.c:575: WARNING: line length of 84 exceeds 80 columns
src/Protocols/NFS/nfs4_op_open.c:645: WARNING: line length of 81 exceeds 80 columns
src/Protocols/NFS/nfs4_op_open.c:654: WARNING: line length of 94 exceeds 80 columns
src/Protocols/NFS/nfs4_op_open.c:658: WARNING: line length of 81 exceeds 80 columns
src/Protocols/NFS/nfs4_op_open.c:1489: WARNING: line length of 81 exceeds 80 columns
src/Protocols/NFS/nfs4_op_open.c:1754: WARNING: line length of 81 exceeds 80 columns
src/Protocols/XDR/xdr_tsm.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/include/transparent_recovery.h:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/include/transparent_recovery.h:2: WARNING: line length of 88 exceeds 80 columns
src/include/transparent_recovery.h:16: WARNING: line length of 88 exceeds 80 columns
src/include/transparent_recovery.h:143: WARNING: line length of 82 exceeds 80 columns
src/include/transparent_recovery.h:145: WARNING: line length of 82 exceeds 80 columns
src/include/transparent_recovery.h:147: WARNING: line length of 83 exceeds 80 columns
src/include/tsm.h:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/include/tsm.h:26: WARNING: please, no spaces at the start of a line
src/include/tsm.h:27: WARNING: please, no spaces at the start of a line
src/include/tsm.h:31: WARNING: please, no spaces at the start of a line
src/include/tsm.h:32: WARNING: please, no spaces at the start of a line
src/include/tsm.h:36: WARNING: please, no spaces at the start of a line
src/include/tsm.h:37: WARNING: please, no spaces at the start of a line
src/include/tsm.h:38: WARNING: please, no spaces at the start of a line
src/include/tsm.h:39: WARNING: please, no spaces at the start of a line
src/include/tsm.h:40: WARNING: please, no spaces at the start of a line
src/include/tsm.h:60: WARNING: please, no spaces at the start of a line
src/include/tsm.h:61: WARNING: please, no spaces at the start of a line
src/include/tsm.h:62: WARNING: please, no spaces at the start of a line
src/include/tsm.h:63: WARNING: please, no spaces at the start of a line
src/include/tsm.h:64: WARNING: please, no spaces at the start of a line
src/include/tsm.h:110: WARNING: line length of 82 exceeds 80 columns
src/include/tsm.h:115: ERROR: Bad function definition - enum clnt_stat tsmproc_null_1() should probably be enum clnt_stat tsmproc_null_1(void)
src/include/tsm.h:116: ERROR: Bad function definition - bool tsmproc_null_1_svc() should probably be bool tsmproc_null_1_svc(void)
src/include/tsm.h:118: ERROR: Bad function definition - enum clnt_stat tsmproc_send_msg_1() should probably be enum clnt_stat tsmproc_send_msg_1(void)
src/include/tsm.h:119: ERROR: Bad function definition - bool tsmproc_send_msg_1_svc() should probably be bool tsmproc_send_msg_1_svc(void)
src/include/tsm.h:121: ERROR: Bad function definition - enum clnt_stat tsmproc_send_states_1() should probably be enum clnt_stat tsmproc_send_states_1(void)
src/include/tsm.h:122: ERROR: Bad function definition - bool tsmproc_send_states_1_svc() should probably be bool tsmproc_send_states_1_svc(void)
src/include/tsm.h:123: ERROR: Bad function definition - int tsmprog_1_freeresult() should probably be int tsmprog_1_freeresult(void)
src/include/tsm.h:135: ERROR: Bad function definition - bool xdr_tsm_state_open() should probably be bool xdr_tsm_state_open(void)
src/include/tsm.h:136: ERROR: Bad function definition - bool xdr_tsm_state_lock() should probably be bool xdr_tsm_state_lock(void)
src/include/tsm.h:137: ERROR: Bad function definition - bool xdr_tsm_rpc_info() should probably be bool xdr_tsm_rpc_info(void)
src/include/tsm.h:138: ERROR: Bad function definition - bool xdr_tsm_rpc_states() should probably be bool xdr_tsm_rpc_states(void)
Checkpatch total: 12 errors, 142 warnings, 5628 lines checked
```
**🟢 FSAL GPFS Build:** `Passed`
**🟢 FSAL RGW Build:** `Passed`
**🟢 FSAL VFS Build:** `Passed`
**🟢 FSAL CephFS Build:** `Passed`
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/1207/console

Patch-set: 1
Reviewer: Gerrit User 1005370 <1005370@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1, 2448a6fe8efbb2dacafcbd4937d71e703ccb0079