Update patch set 1
Patch Set 1: Verified-1

(29 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/607/artifact/failures/ 


**🔴 Checkpatch lint:** `Failed`
```
src/FSAL/commonlib.c:2123: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2123: WARNING: please, no spaces at the start of a line
src/FSAL/commonlib.c:2158: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2158: WARNING: please, no spaces at the start of a line
src/FSAL/commonlib.c:2159: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2159: WARNING: please, no spaces at the start of a line
src/FSAL/commonlib.c:2160: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2160: WARNING: please, no spaces at the start of a line
src/FSAL/commonlib.c:2161: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2161: WARNING: please, no spaces at the start of a line
src/FSAL/commonlib.c:2162: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2162: WARNING: please, no spaces at the start of a line
src/FSAL/commonlib.c:2164: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2165: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2166: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2167: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2168: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2169: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2170: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2171: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2172: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2172: WARNING: please, no spaces at the start of a line
src/FSAL/commonlib.c:2173: ERROR: code indent should use tabs where possible
src/FSAL/commonlib.c:2173: WARNING: please, no spaces at the start of a line
src/include/FSAL/fsal_commonlib.h:53: WARNING: please, no spaces at the start of a line
Checkpatch total: 16 errors, 9 warnings, 55 lines checked
```
**🔴 Clang-format Check:** `Failed`
```
src/FSAL/commonlib.c:2123: clang-format expects formatting for these lines:
src/FSAL/commonlib.c:2158: clang-format expects formatting for these lines:
src/FSAL/commonlib.c:2173: clang-format expects formatting for these lines:
src/include/FSAL/fsal_commonlib.h:53: clang-format expects formatting for these lines:
clang-format found style deviations
```
**🟢 FSAL VFS Build:** `Passed`
**🟢 FSAL GPFS Build:** `Passed`
**🟢 FSAL RGW Build:** `Passed`
**🟢 FSAL CephFS Build:** `Passed`
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/607/console

Patch-set: 1
Reviewer: Gerrit User 1005370 <1005370@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1, da183ca2e1f3111d49a5aabd0518ff9997af6487
Attention: {"person_ident":"Gerrit User 1038902 \u003c1038902@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"ADD","reason":"Someone else replied on the change"}