Update patch set 1
Patch Set 1: Verified-1

(48 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/1214/artifact/failures/ 


**🔴 Checkpatch lint:** `Failed`
```
src/MainNFSD/nfs_rpc_dispatcher_thread.c:190: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:190: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:192: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:192: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:193: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:193: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:194: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:194: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:195: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:195: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:196: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:196: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:197: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:197: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:198: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:198: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:199: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:199: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:200: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:200: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:201: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:201: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:202: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:202: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:203: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:203: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:204: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:204: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:205: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:205: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:206: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:206: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:224: ERROR: trailing whitespace
src/MainNFSD/nfs_rpc_dispatcher_thread.c:225: WARNING: line length of 106 exceeds 80 columns
src/MainNFSD/nfs_rpc_dispatcher_thread.c:226: WARNING: line length of 108 exceeds 80 columns
src/MainNFSD/nfs_rpc_dispatcher_thread.c:229: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:229: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:230: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:230: WARNING: please, no spaces at the start of a line
src/MainNFSD/nfs_rpc_dispatcher_thread.c:231: ERROR: trailing whitespace
src/MainNFSD/nfs_rpc_dispatcher_thread.c:233: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_rpc_dispatcher_thread.c:233: WARNING: please, no spaces at the start of a line
Checkpatch total: 21 errors, 21 warnings, 246 lines checked
```
**🔴 Clang-format Check:** `Failed`
```
src/MainNFSD/nfs_rpc_dispatcher_thread.c:190: clang-format expects formatting for these lines:
src/MainNFSD/nfs_rpc_dispatcher_thread.c:224: clang-format expects formatting for these lines:
src/MainNFSD/nfs_rpc_dispatcher_thread.c:1767: clang-format expects to remove the following lines:
src/include/nfs_core.h:128: clang-format expects to remove the following lines:
src/monitoring/prometheus_exposer.cc:278: clang-format expects formatting for these lines:
src/monitoring/prometheus_exposer.cc:336: clang-format expects to remove the following lines:
clang-format found style deviations
```
**🔴 FSAL GPFS Build:** `Failed`
**🔴 FSAL VFS Build:** `Failed`
**🔴 FSAL RGW Build:** `Failed`
**🔴 FSAL CephFS Build:** `Failed`
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/gatecheck-trigger-gerrithub/1214/console

Patch-set: 1
Reviewer: Gerrit User 1005370 <1005370@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1, c916e74571d6aa9457adf9dea2883ea8f148380a