Update patch set 2
Patch Set 2: Verified-1

Build failed:
/opt/nfs-ganesha/src/MainNFSD/nfs_lib.c:129:18: error: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        nfs_prereq_init(exec_name, nfs_host_name, debug_level, log_path, false);
                        ^~~~~~~~~
/opt/nfs-ganesha/src/include/nfs_init.h:63:28: note: passing argument to parameter 'program_name' here
void nfs_prereq_init(char *program_name, char *host_name, int debug_level,
                           ^
1 error generated.
make[2]: *** [MainNFSD/CMakeFiles/MainServices.dir/build.make:141: MainNFSD/CMakeFiles/MainServices.dir/nfs_lib.c.o] Error 1
make[2]: Target 'MainNFSD/CMakeFiles/MainServices.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2565: MainNFSD/CMakeFiles/MainServices.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 2
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1