Update patch set 1
Patch Set 1: Verified-1

Build proxy failed:
libMainServices.a(nfs_init.c.o): In function `pool_basic_init__':
/opt/nfs-ganesha/src/include/abstract_mem.h:357: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:358: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:361: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:362: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:364: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:366: undefined reference to `pool_list_current'
libMainServices.a(nfs_init.c.o):/opt/nfs-ganesha/src/include/abstract_mem.h:366: more undefined references to `pool_list_current' follow
../SAL/libsal.a(state_lock.c.o): In function `pool_basic_init__':
/opt/nfs-ganesha/src/include/abstract_mem.h:357: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:358: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:361: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:362: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:364: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:366: undefined reference to `pool_list_current'
../SAL/libsal.a(state_lock.c.o):/opt/nfs-ganesha/src/include/abstract_mem.h:366: more undefined references to `pool_list_current' follow
../SAL/libsal.a(nfs4_clientid.c.o): In function `pool_basic_init__':
/opt/nfs-ganesha/src/include/abstract_mem.h:357: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:358: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:361: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:362: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:364: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:366: undefined reference to `pool_list_current'
../SAL/libsal.a(nfs4_clientid.c.o):/opt/nfs-ganesha/src/include/abstract_mem.h:366: more undefined references to `pool_list_current' follow
../hashtable/libhashtable.a(hashtable.c.o): In function `pool_basic_init__':
/opt/nfs-ganesha/src/include/abstract_mem.h:357: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:358: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:361: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:362: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:364: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:366: undefined reference to `pool_list_current'
../hashtable/libhashtable.a(hashtable.c.o):/opt/nfs-ganesha/src/include/abstract_mem.h:366: more undefined references to `pool_list_current' follow
../RPCAL/librpcal.a(nfs_dupreq.c.o): In function `pool_basic_init__':
/opt/nfs-ganesha/src/include/abstract_mem.h:357: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:358: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:361: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:362: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:364: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:366: undefined reference to `pool_list_current'
../RPCAL/librpcal.a(nfs_dupreq.c.o):/opt/nfs-ganesha/src/include/abstract_mem.h:366: more undefined references to `pool_list_current' follow
../support/libsupport.a(nfs4_acls.c.o): In function `pool_basic_init__':
/opt/nfs-ganesha/src/include/abstract_mem.h:357: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:358: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:361: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:362: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:364: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:366: undefined reference to `pool_list_current'
../support/libsupport.a(nfs4_acls.c.o):/opt/nfs-ganesha/src/include/abstract_mem.h:366: more undefined references to `pool_list_current' follow
../FSAL/Stackable_FSALs/FSAL_MDCACHE/libfsalmdcache.a(mdcache_main.c.o): In function `pool_basic_init__':
/opt/nfs-ganesha/src/include/abstract_mem.h:357: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:358: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list'
/opt/nfs-ganesha/src/include/abstract_mem.h:360: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:361: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:362: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:364: undefined reference to `pool_list_current'
/opt/nfs-ganesha/src/include/abstract_mem.h:366: undefined reference to `pool_list_current'
../FSAL/Stackable_FSALs/FSAL_MDCACHE/libfsalmdcache.a(mdcache_main.c.o):/opt/nfs-ganesha/src/include/abstract_mem.h:366: more undefined references to `pool_list_current' follow
collect2: error: ld returned 1 exit status
make[2]: *** [MainNFSD/ganesha.nfsd] Error 1
make[2]: Target `MainNFSD/CMakeFiles/ganesha.nfsd.dir/build' not remade because of errors.
make[1]: *** [MainNFSD/CMakeFiles/ganesha.nfsd.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `default_target' not remade because of errors.

Patch-set: 1
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1