Update patch set 4
Patch Set 4: Verified-1

Build failed:
/opt/nfs-ganesha/src/Protocols/NFS/nfs4_op_secinfo_no_name.c:89:34: error: implicit conversion from enumeration type 'enum nfs_req_result' to different enumeration type 'nfsstat4' (aka 'enum nfsstat4') [-Werror,-Wenum-conversion]
                res_SECINFO_NO_NAME4->status = nfs4_op_lookupp(op, data, resp);
                                             ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [Protocols/NFS/CMakeFiles/nfsproto.dir/build.make:752: Protocols/NFS/CMakeFiles/nfsproto.dir/nfs4_op_secinfo_no_name.c.o] Error 1
make[2]: Target 'Protocols/NFS/CMakeFiles/nfsproto.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:1046: Protocols/NFS/CMakeFiles/nfsproto.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 4
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1