Update patch set 1
Patch Set 1: Verified-1

Build failed:
/opt/nfs-ganesha/src/FSAL/FSAL_CEPH/export.c:228:20: error: taking address of packed member 'chk_vi' of class or structure 'ceph_handle_key' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
        vinodeno_t *vi = &key->chk_vi;
                          ^~~~~~~~~~~
1 error generated.
make[2]: *** [FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/build.make:76: FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/export.c.o] Error 1
make[2]: Target 'FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:1957: FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 1
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1