Update patch set 2
Patch Set 2: Verified-1

Build failed:
/export/nfs-ganesha/src/FSAL/FSAL_VFS/file.c:1727:1: error: unused label 'fetch' [-Werror,-Wunused-label]
fetch:
^~~~~~
1 error generated.
make[2]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/__/file.c.o] Error 1
make[2]: Target 'FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/build' not remade because of errors.
make[1]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsalvfs.dir/all] Error 2
/export/nfs-ganesha/src/FSAL/FSAL_VFS/file.c:1727:1: error: unused label 'fetch' [-Werror,-Wunused-label]
fetch:
^~~~~~
1 error generated.
make[2]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsaldummylustre.dir/__/file.c.o] Error 1
make[2]: Target 'FSAL/FSAL_VFS/vfs/CMakeFiles/fsaldummylustre.dir/build' not remade because of errors.
make[1]: *** [FSAL/FSAL_VFS/vfs/CMakeFiles/fsaldummylustre.dir/all] Error 2
/export/nfs-ganesha/src/FSAL/FSAL_VFS/file.c:1727:1: error: unused label 'fetch' [-Werror,-Wunused-label]
fetch:
^~~~~~
1 error generated.
make[2]: *** [FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/__/file.c.o] Error 1
make[2]: Target 'FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/build' not remade because of errors.
make[1]: *** [FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 2
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1