Update patch set 2
Patch Set 2:

(2 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/test-mani-gpfs/29/artifact/failures/ 


**🔴 Clang-format Check:** `Failed`
```
src/MainNFSD/nfs_qos.c:1623: clang-format expects formatting for these lines:
src/support/ip_utils.c:67: clang-format expects to remove the following lines:
clang-format found style deviations
```
**🔴 Checkpatch lint:** `Failed`
```
src/MainNFSD/nfs_qos.c:1624: ERROR: code indent should use tabs where possible
src/MainNFSD/nfs_qos.c:1624: WARNING: please, no space before tabs
Checkpatch total: 1 errors, 1 warnings, 413 lines checked
```
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/test-mani-gpfs/29/console

Patch-set: 2