Update patch set 15
Patch Set 15:

(2 comments)

Failure Logs: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/test-mani-gpfs/63/artifact/failures/ 


**🔴 Checkpatch lint:** `Failed`
```
src/os/freebsd/subr.c:51: ERROR: trailing whitespace
Checkpatch total: 1 errors, 0 warnings, 23 lines checked
```
**🔴 Clang-format Check:** `Failed`
```
src/os/freebsd/subr.c:51: clang-format expects formatting for these lines:
clang-format found style deviations
```
**🟢 FSAL VFS Build:** `Passed`
**🟢 FSAL GPFS Build:** `Passed`
**🟢 FSAL RGW Build:** `Passed`
**🟢 FSAL CephFS Build:** `Passed`
Jenkins Build URL: https://jenkins-nfs-ganesha.apps.ocp.cloud.ci.centos.org/job/test-mani-gpfs/63/console

Patch-set: 15
Attention: {"person_ident":"Gerrit User 1038958 \u003c1038958@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"ADD","reason":"Someone else replied on the change"}
Attention: {"person_ident":"Gerrit User 1005370 \u003c1005370@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"removed on reply"}