Update patch set 4
Patch Set 4: Verified-1

Build failed:
/export/nfs-ganesha/src/FSAL/FSAL_VFS/xfs/main.c:128:19: error: use of undeclared identifier 'vfs_fsal_module'; did you mean 'xfs_fsal_module'?
            container_of(vfs_fsal_module, struct vfs_fsal_module, module);
                         ^~~~~~~~~~~~~~~
                         xfs_fsal_module
/export/nfs-ganesha/src/include/gsh_list.h:249:49: note: expanded from macro 'container_of'
        const typeof(((type *) 0)->member) * __mptr = (addr);   \
                                                       ^
/export/nfs-ganesha/src/FSAL/FSAL_VFS/xfs/main.c:123:54: note: 'xfs_fsal_module' declared here
static fsal_status_t init_config(struct fsal_module *xfs_fsal_module,
                                                     ^
1 error generated.
make[2]: *** [FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/main.c.o] Error 1
make[2]: Target 'FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/build' not remade because of errors.
make[1]: *** [FSAL/FSAL_VFS/xfs/CMakeFiles/fsalxfs.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 4
Reviewer: CEA-HPC <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1