Update patch set 3
Patch Set 3: Verified-1

Build failed:
CMakeFiles/ml_posix_client.dir/ml_posix_client.c.o: In function `openserver':
/opt/nfs-ganesha/src/tools/multilock/ml_posix_client.c:146: undefined reference to `strlcpy'
CMakeFiles/ml_posix_client.dir/ml_posix_client.c.o: In function `do_fork':
/opt/nfs-ganesha/src/tools/multilock/ml_posix_client.c:173: undefined reference to `strlcpy'
/opt/nfs-ganesha/src/tools/multilock/ml_posix_client.c:189: undefined reference to `strlcpy'
CMakeFiles/ml_posix_client.dir/ml_posix_client.c.o: In function `do_open':
/opt/nfs-ganesha/src/tools/multilock/ml_posix_client.c:253: undefined reference to `strlcpy'
/opt/nfs-ganesha/src/tools/multilock/ml_posix_client.c:266: undefined reference to `strlcpy'
CMakeFiles/ml_posix_client.dir/ml_posix_client.c.o:/opt/nfs-ganesha/src/tools/multilock/ml_posix_client.c:287: more undefined references to `strlcpy' follow
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/multilock/CMakeFiles/ml_posix_client.dir/build.make:117: tools/multilock/ml_posix_client] Error 1
make[2]: Target 'tools/multilock/CMakeFiles/ml_posix_client.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2746: tools/multilock/CMakeFiles/ml_posix_client.dir/all] Error 2
CMakeFiles/ml_console.dir/ml_console.c.o: In function `process_client_response':
/opt/nfs-ganesha/src/tools/multilock/ml_console.c:336: undefined reference to `strlcpy'
CMakeFiles/ml_console.dir/ml_console.c.o: In function `receive_response':
/opt/nfs-ganesha/src/tools/multilock/ml_console.c:371: undefined reference to `strlcpy'
/opt/nfs-ganesha/src/tools/multilock/ml_console.c:373: undefined reference to `strlcpy'
/opt/nfs-ganesha/src/tools/multilock/ml_console.c:383: undefined reference to `strlcpy'
/opt/nfs-ganesha/src/tools/multilock/ml_console.c:389: undefined reference to `strlcpy'
CMakeFiles/ml_console.dir/ml_console.c.o:/opt/nfs-ganesha/src/tools/multilock/ml_console.c:390: more undefined references to `strlcpy' follow
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/multilock/CMakeFiles/ml_console.dir/build.make:117: tools/multilock/ml_console] Error 1
make[2]: Target 'tools/multilock/CMakeFiles/ml_console.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2784: tools/multilock/CMakeFiles/ml_console.dir/all] Error 2
CMakeFiles/ml_glusterfs_client.dir/ml_glusterfs_client.c.o: In function `openserver':
/opt/nfs-ganesha/src/tools/multilock/ml_glusterfs_client.c:159: undefined reference to `strlcpy'
CMakeFiles/ml_glusterfs_client.dir/ml_glusterfs_client.c.o: In function `do_fork':
/opt/nfs-ganesha/src/tools/multilock/ml_glusterfs_client.c:186: undefined reference to `strlcpy'
/opt/nfs-ganesha/src/tools/multilock/ml_glusterfs_client.c:202: undefined reference to `strlcpy'
CMakeFiles/ml_glusterfs_client.dir/ml_glusterfs_client.c.o: In function `do_open':
/opt/nfs-ganesha/src/tools/multilock/ml_glusterfs_client.c:267: undefined reference to `strlcpy'
/opt/nfs-ganesha/src/tools/multilock/ml_glusterfs_client.c:277: undefined reference to `strlcpy'
CMakeFiles/ml_glusterfs_client.dir/ml_glusterfs_client.c.o:/opt/nfs-ganesha/src/tools/multilock/ml_glusterfs_client.c:295: more undefined references to `strlcpy' follow
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/multilock/CMakeFiles/ml_glusterfs_client.dir/build.make:117: tools/multilock/ml_glusterfs_client] Error 1
make[2]: Target 'tools/multilock/CMakeFiles/ml_glusterfs_client.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2822: tools/multilock/CMakeFiles/ml_glusterfs_client.dir/all] Error 2
CMakeFiles/ml_cephfs_client.dir/ml_cephfs_client.c.o: In function `openserver':
/opt/nfs-ganesha/src/tools/multilock/ml_cephfs_client.c:159: undefined reference to `strlcpy'
CMakeFiles/ml_cephfs_client.dir/ml_cephfs_client.c.o: In function `do_fork':
/opt/nfs-ganesha/src/tools/multilock/ml_cephfs_client.c:186: undefined reference to `strlcpy'
/opt/nfs-ganesha/src/tools/multilock/ml_cephfs_client.c:202: undefined reference to `strlcpy'
CMakeFiles/ml_cephfs_client.dir/ml_cephfs_client.c.o: In function `do_open':
/opt/nfs-ganesha/src/tools/multilock/ml_cephfs_client.c:268: undefined reference to `strlcpy'
/opt/nfs-ganesha/src/tools/multilock/ml_cephfs_client.c:278: undefined reference to `strlcpy'
CMakeFiles/ml_cephfs_client.dir/ml_cephfs_client.c.o:/opt/nfs-ganesha/src/tools/multilock/ml_cephfs_client.c:297: more undefined references to `strlcpy' follow
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/multilock/CMakeFiles/ml_cephfs_client.dir/build.make:118: tools/multilock/ml_cephfs_client] Error 1
make[2]: Target 'tools/multilock/CMakeFiles/ml_cephfs_client.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:2860: tools/multilock/CMakeFiles/ml_cephfs_client.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:152: all] Error 2
make: Target 'default_target' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1004838 <1004838@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1